  server:
    port: 8080

  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

    datasource:
      url: jdbc:sqlserver://localhost:1433;databaseName=RestCampitos;encrypt=true;trustServerCertificate=true
      username: sa
      password: TuContraseña123
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    jpa:
      database-platform: org.hibernate.dialect.SQLServerDialect
      hibernate:
        ddl-auto: none
      show-sql: true

    web:
      resources:
        static-locations: classpath:/static/, file:uploads/

  apis:
    net:
      pe:
        token: apis-token-15889.OxWqd8HznRYaRkp67v3fEZJOWGwuC9rz
